#!/bin/bash
set -euo pipefail

if [[ ! -v WASI_SDK_VERSION ]]; then
    echo "WASI_SDK_VERSION required"
    exit 1
fi

echo "building Swift SDK generator..."

git clone --quiet https://github.com/swiftlang/swift-sdk-generator.git
cd swift-sdk-generator

WASI_SDK_URL="https://github.com/WebAssembly/wasi-sdk/releases/download/\
wasi-sdk-${WASI_SDK_VERSION}/wasi-sysroot-${WASI_SDK_VERSION}.0.tar.gz"

curl -fLS "$WASI_SDK_URL" \
    -o wasi-sysroot.tar.gz

mkdir wasi-sysroot
tar -xzf wasi-sysroot.tar.gz -C wasi-sysroot --strip-components=1
rm wasi-sysroot.tar.gz

swift build -c release --product swift-sdk-generator
for sdk in wasm32-unknown-wasip1-threads wasm32-unknown-wasip1; do
    .build/release/swift-sdk-generator make-wasm-sdk \
        --target "$sdk" \
        --wasi-sysroot wasi-sysroot
done
