#!/bin/bash
set -e

for dockerfile in *.Dockerfile; do
    docker build . -f $dockerfile -t swiftwasm:__test

    echo $SWIFT_WASM_SDK
    docker run --rm \
        -v=$PWD/Tests:/swift \
        -w=/swift \
        swiftwasm:__test \
        swift package --swift-sdk "$SWIFT_WASM_SDK" js

done
