#!/bin/bash
set -e

for dockerfile in *.Dockerfile; do
    docker build . -f $dockerfile -t swiftwasm:__test \
        --build-arg SWIFT_VERSION='6.3' \
        --build-arg SWIFT_NIGHTLY='SNAPSHOT-2026-01-16-a'

    echo $SWIFT_WASM_SDK
    docker run --rm \
        -v=$PWD/Tests:/swift \
        -w=/swift \
        swiftwasm:__test \
        swift package --swift-sdk "$SWIFT_WASM_SDK" js

done
