name: Build Swift WebAssembly SDK

on:
    workflow_call:
        inputs:
            swift-prefix:
                description: 'swift toolchain url prefix'
                required: true
                type: string
            swift-id:
                description: 'swift toolchain identifier'
                required: true
                type: string
            wasi-sdk:
                description: 'the wasi sdk version to use'
                required: true
                type: string

jobs:
    WebAssembly:
        runs-on: ubuntu-24.04
        steps:
            -   name: 💝 Install Swift 💝
                uses: rarestype/swift-install-action@v1
                with:
                    swift-prefix: ${{ inputs.swift-prefix }}
                    swift-id: ${{ inputs.swift-id }}

            -   name: 💝 Checkout Swift project 💝
                uses: actions/checkout@v6
                with:
                    repository: swiftlang/swift
                    path: swift

            -   name: 💝 Checkout related repositories 💝
                run: |
                    SWIFT_PREFIX="${{ inputs.swift-prefix }}"
                    SWIFT_TAG="${SWIFT_PREFIX##*/}"
                    echo "checking out tag: ${SWIFT_TAG}"

                    swift/utils/update-checkout --clone --tag "$SWIFT_TAG"

            -   name: 💝 Build  💝
                run: |
                    SWIFT_PATH="${SWIFT_INSTALLATION}/bin"
                    swift/utils/build-script \
                        --skip-build-llvm \
                        --skip-build-swift \
                        --skip-build-cmark \
                        --build-wasm-stdlib \
                        --native-swift-tools-path="$SWIFT_PATH" \
                        --native-clang-tools-path="$SWIFT_PATH" \
                        --native-llvm-tools-path="$SWIFT_PATH"

            -   name: 💝 List files 💝
                run: |
                    ls -l swift-sdk-generator
                    ls -l swift-sdk-generator/Bundles

            # -   name: 💝 Upload SDK artifacts 💝
            #     uses: actions/upload-artifact@v7
            #     with:
            #         name: swift-wasm-sdk-bundle
            #         path: ./*.artifactbundle.tar.gz
            #         retention-days: 1
            #         compression-level: 0
